#!/bin/sh
set -eu

echo "// Generated by docker entrypoint
window.__APP_CONFIG__ = {
  VITE_DBB_URL: \"${VITE_DBB_URL}\",
  VITE_LOGO_URL: \"${VITE_LOGO_URL}\",
  VITE_CONTACT_URL: \"${VITE_CONTACT_URL}\",
  VITE_CONFERENCE_URL: \"${VITE_CONFERENCE_URL}\"
};" > /usr/share/nginx/html/env.js

exec "$@"
