version: "3"
services:
  client:
    image: "election-verification-site:latest"
    # image: "534003348933.dkr.ecr.eu-west-1.amazonaws.com/election-verification-site:dev-main"
    build:
      context: "./client"
      ssh:
        - "default"
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: "yarn dev"
    ports:
      - "3010:3010"
    environment:
      SERVICE_NAME: "dbas"
    healthcheck:
      test: "curl -s http://localhost:3010"
      interval: "5s"
      start_period: "10s"
      timeout: "5s"
      retries: 10
