version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.8.1
  aws-cli: circleci/aws-cli@5.4.1
  docker: assemblyvoting/docker@1.6.4

executors:
  vm-linux-ubuntu:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
  vm-linux-ubuntu-nocache:
    machine:
      image: ubuntu-2204:current
  license-checker-node22:
    docker:
      - image: public.ecr.aws/assembly-voting/license-checker-image:ruby-latest-node22

filters:
  - &commit_only
    branches:
      only: /.*/
    tags:
      ignore: /.*/
  - &release_only
    branches:
      ignore: /.*/
    tags:
      only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+(?:-(sc|rc).*)?$/
  - &always
    tags:
      only: /.*/
commands:
  ecr-login:
    steps:
      - aws-cli/setup:
          profile_name: default
          role_arn: arn:aws:iam::534003348933:role/CircleCI_runner_ecr_access
          region: eu-west-1
      - aws-ecr/ecr_login:
          account_id: '534003348933'
          profile_name: default
          public_registry: false
          region: eu-west-1
  build-image:
    parameters:
      service_name:
        type: string
      ecr_registry_id:
        type: string
        default: "534003348933"
      target:
        type: enum
        default: "development"
        enum: ["builder", "development", "production"]
      environment:
        type: enum
        default: "development"
        enum: ["development", "test", "production"]
      tag_prefix:
        type: string
        default: ""
      docker_context:
        type: string
        default: "."
    steps:
      - run:
          name: Set environment variables
          command: |
            echo "export AV_SECRET_KEY_BASE=${RANDOM}" >> "$BASH_ENV"
            echo 'export ECR_REGISTRY="<< parameters.ecr_registry_id >>.dkr.ecr.eu-west-1.amazonaws.com"' >> "$BASH_ENV"
            echo 'export ECR_REGISTRY_ID="<< parameters.ecr_registry_id >>"' >> "$BASH_ENV"
            echo 'export SSH_AUTH_SOCK=/tmp/circleci/ssh/ssh_agent.sock' >> "$BASH_ENV"
      - checkout
      - ecr-login
      - docker/ssh-access:
          VAR_SSH_KEY: PULL_SSH_KEY
      - run:
          name: Build Docker image
          command: |
            docker build << parameters.docker_context >> --target=<< parameters.target >> -t << parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1} --ssh default 
      - run:
          name: Push untested docker image
          command: |
            docker tag << parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1} ${ECR_REGISTRY}/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested
            docker push ${ECR_REGISTRY}/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested
  tag-tested-image:
    parameters:
      service_name:
        type: string
      ecr_registry_id:
        type: string
        default: "534003348933"
      tag_prefix:
        type: string
        default: ""
    steps:
      - run:
          name: Set environment variables
          command: |
            echo 'export ECR_REGISTRY_ID="<< parameters.ecr_registry_id >>"' >> "$BASH_ENV"
            echo 'export ECR_REGISTRY="${ECR_REGISTRY_ID}.dkr.ecr.eu-west-1.amazonaws.com"' >> "$BASH_ENV"
      - ecr-login
      - docker/tag-push:
          service: election-verification-site
          pull-tag: << parameters.tag_prefix >>"${CIRCLE_SHA1}"-untested
          push-tags: main,latest,<< parameters.tag_prefix >>"${CIRCLE_SHA1}"
  run-e2e:
    parameters:
      service_name:
        type: string
      ecr_registry_id:
        type: string
        default: "534003348933"
      tag_prefix:
        type: string
        default: ""
    steps:
      - ecr-login
      - run:
          name: Pull the image for testing
          command: |
            docker pull 534003348933.dkr.ecr.eu-west-1.amazonaws.com/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested
      - run:
          name: Run e2e client tests
          command: |
            docker run --name=e2e -e CI="1" 534003348933.dkr.ecr.eu-west-1.amazonaws.com/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested bash -c "yarn build && yarn test:e2e:ci"
            docker cp e2e:/usr/src/app/test-results .
      - store_artifacts:
          path: test-results

  run-component:
    parameters:
      service_name:
        type: string
      ecr_registry_id:
        type: string
        default: "534003348933"
      tag_prefix:
        type: string
        default: ""
    steps:
      - ecr-login
      - run:
          name: Pull the image for testing
          command: |
            docker pull 534003348933.dkr.ecr.eu-west-1.amazonaws.com/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested
      - run:
          name: Run component client tests
          command: |
            docker run --name=component -e CI="1" 534003348933.dkr.ecr.eu-west-1.amazonaws.com/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested bash -c "yarn test:unit:ci"
            docker cp component:/usr/src/app/src/test-results .
      - store_artifacts:
          path: test-results
  run-linting:
    parameters:
      service_name:
        type: string
      ecr_registry_id:
        type: string
        default: "534003348933"
      tag_prefix:
        type: string
        default: ""
    steps:
      - ecr-login
      - run:
          name: Pull the image for testing
          command: |
            docker pull 534003348933.dkr.ecr.eu-west-1.amazonaws.com/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested
      - run:
          name: Run linting for client
          command: |
            docker run --rm 534003348933.dkr.ecr.eu-west-1.amazonaws.com/<< parameters.service_name >>:<< parameters.tag_prefix >>${CIRCLE_SHA1}-untested bash -c "yarn lint:ci && yarn prettier:ci"

jobs:
  lint-dockerfile-client:
    executor: vm-linux-ubuntu-nocache
    steps:
      - docker/lint:
          dockerfile: ./client/Dockerfile
  build-image-development-client:
    executor: vm-linux-ubuntu
    steps:
      - build-image:
          service_name: "election-verification-site"
          tag_prefix: "dev-"
          target: "development"
          environment: "development"
          docker_context: "./client"
  build-image-production-client:
    executor: vm-linux-ubuntu
    steps:
      - build-image:
          service_name: "election-verification-site"
          tag_prefix: ""
          target: "production"
          environment: "production"
          docker_context: "./client"
  scan-client:
    executor: vm-linux-ubuntu-nocache
    environment:
      ECR_REGISTRY_ID: "534003348933"
    steps:
      - checkout
      - ecr-login
      - run:
          name: Pull the image for scanning
          command: |
            docker pull ${ECR_REGISTRY_ID}.dkr.ecr.eu-west-1.amazonaws.com/election-verification-site:${CIRCLE_SHA1}-untested
      - docker/scan:
          image: ${ECR_REGISTRY_ID}.dkr.ecr.eu-west-1.amazonaws.com/election-verification-site:${CIRCLE_SHA1}-untested
          ignored_cves: ""
  client-e2e:
    executor: vm-linux-ubuntu-nocache
    steps:
      - run-e2e: &client-service-aws
          service_name: "election-verification-site"
          tag_prefix: "dev-"
  client-component:
    executor: vm-linux-ubuntu-nocache
    steps:
      - run-component:
          <<: *client-service-aws
  client-linting:
    executor: vm-linux-ubuntu-nocache
    steps:
      - run-linting:
          <<: *client-service-aws
  tag-tested-client-image-dev:
    executor: vm-linux-ubuntu-nocache
    steps:
      - tag-tested-image:
          <<: *client-service-aws
  tag-tested-client-image-prod:
    executor: vm-linux-ubuntu-nocache
    steps:
      - tag-tested-image:
          <<: *client-service-aws
          tag_prefix: ""
  tag-final-client-image-prod:
    executor: vm-linux-ubuntu-nocache
    environment:
      ECR_REGISTRY_ID: '534003348933'
    steps:
      - ecr-login
      - docker/tag-push:
          service: election-verification-site
          pull-tag: ${CIRCLE_SHA1}
          push-tags: ${CIRCLE_TAG}

workflows:
  everything:
    jobs:
      - docker/license-checker:
          context:
            - 'GIT'
          filters: *always
          prep-yarn: true
          executor: license-checker-node22
      - lint-dockerfile-client:
          filters: *commit_only
      - build-image-development-client:
          context:
            - "GIT"
            - "ECR-RW"
          requires:
            - lint-dockerfile-client
          filters: *commit_only
      - build-image-production-client:
          context:
            - "GIT"
            - "ECR-RW"
          requires:
            - lint-dockerfile-client
          filters: *commit_only
      - scan-client:
          requires:
            - build-image-production-client
          context:
            - "ECR-RW"
          filters: *commit_only
      - client-e2e:
          requires:
            - build-image-development-client
          context:
            - "ECR-RW"
          filters: *commit_only
      - client-component:
          requires:
            - build-image-development-client
          context:
            - "ECR-RW"
          filters: *commit_only
      - client-linting:
          requires:
            - build-image-development-client
          context:
            - "ECR-RW"
          filters: *commit_only
      - tag-tested-client-image-dev:
          requires:
            - client-e2e
            - client-component
            - client-linting
          context:
            - "ECR-RW"
          filters: *commit_only
      - tag-tested-client-image-prod:
          requires:
            - client-e2e
            - client-component
            - client-linting
            - scan-client
          context:
            - "ECR-RW"
          filters: *commit_only
  tag-final-image:
    jobs:
      - tag-final-client-image-prod:
          context:
            - "ECR-RW"
          filters: *release_only